apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: grzrn38ss-java-springboot-gitops-repository
spec:
  url: https://github.com/testrhtaporg/grzrn38ss-java-springboot-gitops